# SPDX-FileCopyrightText: SAP SE
# SPDX-License-Identifier: Apache-2.0
version = 1
SPDX-PackageName = "ntp_exporter"
SPDX-PackageDownloadLocation = "https://github.com/sapcc/ntp_exporter"

[[annotations]]
path = [
  ".github/CODEOWNERS",
  ".github/renovate.json",
  ".gitignore",
  ".license-scan-overrides.jsonl",
  ".license-scan-rules.json",
  "go.mod",
  "go.sum",
  "Makefile.maker.yaml",
  "vendor/modules.txt",
]
SPDX-FileCopyrightText = "SAP SE"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/beevik/ntp/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_golang/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-api-declarations/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sapcc/go-bits/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/go.uber.org/automaxprocs/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/beorn7/perks/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/cespare/xxhash/v2/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/davecgh/go-spew/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "ISC"

[[annotations]]
path = [
  "vendor/github.com/google/go-cmp/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/klauspost/compress/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/kylelemons/godebug/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/munnerz/goautoneg/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/pmezard/go-difflib/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/github.com/prashantv/gostub/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/prometheus/client_model/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/common/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/prometheus/procfs/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "vendor/github.com/sergi/go-diff/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/github.com/stretchr/testify/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
  "vendor/golang.org/x/net/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/golang.org/x/sys/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/google.golang.org/protobuf/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = [
  "vendor/gopkg.in/yaml.v3/**",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "Other"
SPDX-License-Identifier = "MIT"
